use_frameworks!

platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'VikycSDK_Example' do
  pod 'VikycSDK'

  target 'VikycSDK_Tests' do
    inherit! :search_paths

    
  end
end
